### PR TITLE
MIDI, Microphone and Speaker updates

### PR DESCRIPTION
**Pull request by softerhardware**

### CODE REVIEW

**Comment by dl1ycf** [comment]
I'll try to merge in manually. This is difficult since there is a lot of "white space transformation" (tabs to spaces etc.). But some notes:

a) The initialization of midi_cw_keydown and other variables when creating the class should be kept.
It is a good idea that they can be set (overwritten) by incoming MIDI commands, but in case no such
commands arrive, the settings via config.h and the class creation parameter list in the *.ino sketch
must remain effective. Otherewise the keyer does not work if not controlled by incoming MIDI messages,
and this I simply do not want.

b) It seems the name of the variable "mute_on_ptt" was felt not good enough. OK. But renaming "ptt" to "cw_headtail" everywhere in the code certainly obscures the code. In many cases "ptt" is more appropriate.

Perhaps there are more points but first I have to download the "PR" repository to make a whitespace-insensitve
diff.

**Comment by softerhardware** [comment]
Hi Christoph,

Even though we are working on TeensyUSBAudioMidi in your repository, I
still think of it as generic code which can be used in other keyers, for
example the k3ng keyer. Because of this, I think a good set of defaults for
MIDI channels and notes should be in the TeensyUSBAudioMidi. I believe this
is clearer code and also encourages users to use the same notes and
channels whenever possible.

It should also be possible for any user to customize MIDI note and channel
settings. In the current code, there are access functions such as
set_midi_keydown_note. After creating the object, a user can use these to
set whatever they like, although I would encourage a standard set of
values. If you like to do this in the constructor, we can also add defaults
to the constructor, but a set of recommended default values should live in
the TeensyUSBAudioMidi code so that it is easily portable.

I renamed mute_on_ptt to cw_headtail as we need to distinguish between a
true PTT and a synthetic one created pre/post CW keydown. This is not just
a CW keyer but also a device which supports microphones for SSB and has two
sources of real PTT. It is confusing if the synthetic "PTT" from CW
head/tail times is called PTT given there are real PTT signals to consider.
I am open to other names if you don't like this name. For example, cw_ptt?

This pull request is clean and will merge without conflict with your code.
In these cases, I've found it easiest to just accept the pull request and
then examine and change things you don't like after the merge. Git and
github have flags to ignore whitespace differences. See
https://github.blog/2018-05-01-ignore-white-space-in-code-review/  I can
also clean up some of the whitespace differences and resubmit the pull if
you like. I use only spaces for indent and have been following your indent
by two. I also do not like trailing whitespace. I like tkdiff which also
has flags to ignore whitespace differences.

Any delay in accepting the pull request is not impacting me as the CWKeyer
repository uses my fork which has my changes. It is just that the longer we
wait, the harder merges become. Maybe it is the wrong approach for me to
make changes in your repository, and instead I should create a repository
only for the generic TeensyUSBAudioMidi and other code in the src directory
which you and others can use and modify.

73,

Steve
kf7o

**Comment by dl1ycf** [comment]
> Am 18.01.2022 um 06:28 schrieb Steve Haynal ***@***.***>:
> 
> 
> Hi Christoph,
> 
> Even though we are working on TeensyUSBAudioMidi in your repository, I
> still think of it as generic code which can be used in other keyers, for
> example the k3ng keyer. Because of this, I think a good set of defaults for
> MIDI channels and notes should be in the TeensyUSBAudioMidi. I believe this
> is clearer code and also encourages users to use the same notes and
> channels whenever possible.
> 
> It should also be possible for any user to customize MIDI note and channel
> settings. In the current code, there are access functions such as
> set_midi_keydown_note. After creating the object, a user can use these to
> set whatever they like, although I would encourage a standard set of
> values. If you like to do this in the constructor, we can also add defaults
> to the constructor, but a set of recommended default values should live in
> the TeensyUSBAudioMidi code so that it is easily portable.
> 

a) This is my idea as well: the TeensyUSBAudioMIDI "class" should be
   moved to the top-level of "src" and it should be independent of
   whatever code is using it. The present situation is purely historical,
   since your original keyer implementation "buried" this into the
   K3NG keyer so I had to do the same for my keyer. But I certainly
   are very much in favour of having this "stand-alone".

   But this means one has to put the TeensyUSBAudioMidi directory
   in the master "src" directory where I have all these extensions,
   and then I probably have to place a symbolic link deeply into
   the IDE such that

   #include <TeensyUSBAudioMidi/TeensyUSBAudioMidi.h>

   works. Perhaps you have more knowledge on the IDE how to do this. This
   I shall defer until the present PR is processed, that is, until
   the different "flavors" of teensyusbaudiomidi are unified.

b) At the moment, the "default" values for MIDI notes etc. are passed
   to the contructor, as well as several other options. This makes the 
   parameter list of the constructor huge and I understand you do not
   like this.
   The only variable
   which *should* be included in the constructor is "i2s", this controls
   which AudioStream is initialized because this is done in the constructor.
   So I guess your idea is that there are two new functions that can (but need not) be
   called to overwrite hard-wired defaults, so the typical
   initialization is then:

	// constructor. AUDIO_OUTPUT is 0 or 1 or 2
	TeensyUSBAudioMidi teensyusbaudiomidi(AUDIO_OUTPUT);
	
	// obligatory setup call
	teensyusbaudiomidi.setup();

	// This call overwrites the "hard-wired" defaults
	// for the MIDI notes and channels
	// and is not necessary
	teensyusbaudiomidi.midikeys(MIDI_CW_NOTE,
                                    MIDI_PTT_NOTE,
                                    MIDI_SPEED_CTRL,
                                    MIDI_PITCH_CTRL,
                                    MIDI_CW_CHANNEL,
                                    MIDI_CONTROL_CHANNEL);

	// This call overwrites some settings (including
	// Analog input pin numbers) and is not necessary,
	// if the hard-wired settings are OK
	teensyusbaudiomidi.options(MUTE_ON_PTT,
                                   SIDETONE_FREQ,
                                   SIDETONE_VOLUME,
                                   TEENSY_ANALOG_SIDEVOL,
                                   TEENSY_ANALOG_SIDEFREQ,
                                   TEENSY_ANALOG_MASTERVOL,
                                   TEENSY_ANALOG_SPEED);

PLEASE tell me if this is what you want. For me it is OK. Implementing the new
functions midikeys() and options() is trivial since it essentially means
copying the arguments to the private variables.

c) I do not understand the PTT issue. Of course there are several sources
   of a PTT signal, I see that MICPTT and a PTT input jack end up at
   digital input pin 3. The important point is, that there is only
   a single PTT signal "downstream" to the radio, that is, the hardware
   output (digital pin 4) and the MIDI event. The radio cannot (and should
   not) distinguish what actually caused the PTT line become active.

   So why not just calling the SAME function teensyusbaudiomidi.ptt(int state)
   that is used by the keyer, to signal a change in the digital input pin 3
   state? What is the advantage of having differently named functions that do
   the same thing? Since, of course, a hardware PTT signal at the PTT input
   jack should also BOTH trigger the PTT opto-coupler and emit a MIDI event.
   This is absolutely necessary for the "HL2 in the attic" scenario.

> I renamed mute_on_ptt to cw_headtail as we need to distinguish between a
> true PTT and a synthetic one created pre/post CW keydown. This is not just
> a CW keyer but also a device which supports microphones for SSB and has two
> sources of real PTT. It is confusing if the synthetic "PTT" from CW
> head/tail times is called PTT given there are real PTT signals to consider.
> I am open to other names if you don't like this name. For example, cw_ptt?
> 

I am in favour of pull requests which can easily be reviewed, so they
should not display many screens of "changed code" where there is no change.
Thanks for the link but I simply don't get the "diff settings" menu
in github. I just clone your repo and do a diff locally with "diff"
(there I know how to suppress white space settings). When everything is
completed I will edit all the files with "vi", set tabstops=4 or 8 
(what seems less invasive) and do
a "retab" so one has a consistent set of tab stops and converted spaces
to tabs where possible.

I think the problem is that the Arduino IDE uses tabstop=4 while the
standard editor uses tabstop=8, and normally I edit the *.ino with
Arduino and the src/* with vi. And if one then mixes tab-based
indentation with spaces than chaos ensues.
But I shall take care of that.

**Comment by dl1ycf** [comment]
I have now merged in manually, but there were some updates to your code needed.
 If I close the PR and you re-open it, then we can see and discuss the remaining
differences. Perhaps we could agree on a whitespace convention: My suggestion is
- use indentation of 4 
- use tabstop=4
- convert spaces to tabs where possible

But we could equally well agree on an indentation of 4 and convert all tabs to spaces. "vi" does this automatically.
I have renamed ptt to "cwptt" although the code not yet handles the MICIN. The (intended) difference between
cwpttt an ptt is that only the former applies the "mute on CW TX" option (if it is activated). I also added some
more "hooks" to set MIDI notes/controllers.

**Pull request closed without merging**
